name: send gpt3 email

on: push

## or set timer (runs 10:00 utc)
# on:
#   schedule:
#   - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout rep
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run script
        env: 
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_EMAIL2: ${{ secrets.MY_EMAIL2 }}
          PASSWORD: ${{ secrets.PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python message.py
